[collectors]

[collectors.site]
PATH = "construction_site.sibelga.collectors.site.SibelgaSiteCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "1h"

[handlers]

[handlers.site]

PATH = "construction_site.sibelga.handlers.site.SibelgaSiteHandler"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
QUERY_PARAMETERS = { start_timestamp = "int", end_timestamp = "int" }
