[collectors]

[collectors.incidents]

PATH = "fixmystreet.collectors.incidents.FixMyStreetIncidentsCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "5m"

[harvesters]

[harvesters.history]
PATH = "fixmystreet.harvesters.history.FixMyStreetHistoryHarvester"
DATA_FORMAT = "json"
DATA_TYPE = "json"
SOURCE = "fixmystreet.incidents"
DEPENDENCIES = ["incidents"]
DEPENDENCIES_LIMIT = [2, 1]

[handlers]

[handlers.history]

[handlers.sensors]

PATH = "fixmystreet.handlers.history.FixMyStreetHistoryHandler"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
QUERY_PARAMETERS = { start_timestamp = "int", end_timestamp = "int" }
