[collectors]

[collectors.incidents]

PATH = "fixmystreet.collectors.incidents.FixMyStreetIncidentsCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "5m"

#[harvesters]

#[haversters.history]
